apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: is-media-api-lumen
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: is-media-api-lumen
  data:
    - secretKey: STORAGE_PATH
      remoteRef:
        key: e6q3n5c9q0n9q2nv5klg
        property: STORAGE_PATH
    - secretKey: DB_CONNECTION
      remoteRef:
        key: e6q3n5c9q0n9q2nv5klg
        property: DB_CONNECTION
    - secretKey: DB_HOST
      remoteRef:
        key: e6q3n5c9q0n9q2nv5klg
        property: DB_HOST
    - secretKey: DB_DATABASE
      remoteRef:
        key: e6q3n5c9q0n9q2nv5klg
        property: DB_DATABASE
    - secretKey: DB_USERNAME
      remoteRef:
        key: e6q3n5c9q0n9q2nv5klg
        property: DB_USERNAME
    - secretKey: DB_PORT
      remoteRef:
        key: e6q3n5c9q0n9q2nv5klg
        property: DB_PORT
    - secretKey: DB_PASSWORD
      remoteRef:
        key: e6q3n5c9q0n9q2nv5klg
        property: DB_PASSWORD
